services:
  postgres:
    image: postgres:16
    container_name: gamestalgia-postgres
    environment:
      POSTGRES_DB: gamestalgia
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"