spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gamestalgia
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: admin
      password: admin

server:
  port: 8080